server:
  port: 8080

spring:
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:mysql://localhost:3306/mone_agentx
    username: root
    password: 123456

  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    run.mone.agentx: DEBUG
